#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""VoiceAgent - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- LLM (switchable via LLM_MODEL in .env: OpenAI / Anthropic / Google)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.evals.transport import EvalTransport, EvalTransportParams
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.run import app
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.anthropic.llm import AnthropicLLMService
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.google.llm import GoogleLLMService
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.services.sarvam.stt import SarvamSTTService
from pipecat.services.sarvam.tts import SarvamTTSService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.workers.runner import WorkerRunner

from bargein import create_bargein_observer
from business import get_active_profile
from catalog import BusinessData
from latency import create_latency_observer
from rag import DocStore
from tools import tools_for

load_dotenv(override=True)


# The persona/use case is configurable — see business.py. The active profile
# (BUSINESS in .env) supplies the system prompt and the opening greeting, so
# swapping the bot from a store to another use case is a one-place change.
PROFILE = get_active_profile()
SYSTEM_INSTRUCTION = PROFILE.system_instruction()

# The local structured data the tools read (products, orders) and the tool
# functions this profile exposes — both keyed off the profile, so they swap with
# the use case. DATA is shared into every tool handler via app_resources (below).
DATA = BusinessData.load(PROFILE.key)
# The FAQ/policy corpus for search_docs (data/<key>/docs/), embedded locally at
# boot. Attached onto DATA so every tool reaches it via params.app_resources
# (empty and cheap when a profile ships no docs/ folder).
DATA.docs = DocStore.load(PROFILE.key)
TOOLS = tools_for(PROFILE.key)

# Where per-turn latency is logged for the future scorecard (Phase 4). Set
# LATENCY_JSONL to override, or to "" / "none" to disable file logging.
_latency_jsonl_env = os.getenv("LATENCY_JSONL", "metrics/turns.jsonl").strip()
LATENCY_JSONL_PATH = (
    Path(_latency_jsonl_env) if _latency_jsonl_env.lower() not in ("", "none") else None
)

# Where each barge-in (caller talking over the bot) is logged for the barge-in
# scorecard. Same on/off contract as LATENCY_JSONL above. See bargein.py.
_bargein_jsonl_env = os.getenv("BARGEIN_JSONL", "metrics/bargein.jsonl").strip()
BARGEIN_JSONL_PATH = (
    Path(_bargein_jsonl_env) if _bargein_jsonl_env.lower() not in ("", "none") else None
)

# Model switcher. Each key maps to (Pipecat service class, real provider model id,
# the API-key env var it needs, a UI-friendly label). The label is what the client's
# dropdown shows; the env var is how we know whether the model is usable (key present).
# LLM_MODEL in .env picks the default; the client can override per session (see run_bot).
# To add/repin a model, edit one row here — the .env only ever holds the key name.
LLM_REGISTRY = {
    "sonnet-5":         (AnthropicLLMService, "claude-sonnet-5",        "ANTHROPIC_API_KEY", "Claude Sonnet 5"),
    "sonnet-4.6":       (AnthropicLLMService, "claude-sonnet-4-6",      "ANTHROPIC_API_KEY", "Claude Sonnet 4.6"),
    # NOTE: gemini-2.5-flash briefly 404'd server-side (mid-2026) but is working
    # again — verified 2026-07-16 via generateContent, the OpenAI-compat endpoint,
    # and GoogleLLMService.run_inference (the judge path). Kept selectable.
    "gemini-2.5-flash":      (GoogleLLMService, "gemini-2.5-flash",         "GOOGLE_API_KEY", "Gemini 2.5 Flash"),
    "gemini-3-flash":        (GoogleLLMService, "gemini-3-flash-preview",   "GOOGLE_API_KEY", "Gemini 3 Flash"),
    "gemini-3.5-flash":      (GoogleLLMService, "gemini-3.5-flash",         "GOOGLE_API_KEY", "Gemini 3.5 Flash"),
    # Flash-Lite: Google's fastest/cheapest tier — lowest latency for a voice bot.
    "gemini-3.1-flash-lite": (GoogleLLMService, "gemini-3.1-flash-lite",    "GOOGLE_API_KEY", "Gemini 3.1 Flash Lite (fastest)"),
    "gemini-flash-lite":     (GoogleLLMService, "gemini-flash-lite-latest", "GOOGLE_API_KEY", "Gemini Flash Lite (latest)"),
    "gpt-5-mini":       (OpenAILLMService,    "gpt-5.4-mini",           "OPENAI_API_KEY",    "GPT-5 mini"),
    "gpt-5-nano":       (OpenAILLMService,    "gpt-5.4-nano",           "OPENAI_API_KEY",    "GPT-5 nano"),
}

DEFAULT_LLM_MODEL = "gpt-5-mini"


def create_llm(choice: str | None = None):
    """Build an LLM service.

    Args:
        choice: A key from ``LLM_REGISTRY`` (sent by the client per session). Falls
            back to ``LLM_MODEL`` in .env, then the module default.

    Fails fast with a clear message on an unknown model name or a missing API key,
    so a bad selection surfaces at connect instead of mid-call.
    """
    choice = (choice or os.getenv("LLM_MODEL", DEFAULT_LLM_MODEL)).strip()
    if choice not in LLM_REGISTRY:
        raise ValueError(
            f"Unknown LLM model {choice!r}. Choose one of: {', '.join(LLM_REGISTRY)}"
        )

    service_cls, model_id, key_var, _label = LLM_REGISTRY[choice]
    api_key = os.getenv(key_var)
    if not api_key:
        raise ValueError(
            f"LLM model {choice!r} needs {key_var} set in your .env "
            f"(it resolves to provider model {model_id})."
        )

    logger.info(f"LLM: {choice} -> {model_id} ({service_cls.__name__})")
    return service_cls(
        api_key=api_key,
        settings=service_cls.Settings(
            model=model_id,
            system_instruction=SYSTEM_INSTRUCTION,
        ),
    )


# STT switcher — same registry pattern as the LLM/TTS ones. Each key maps to
# (factory, API-key env var, UI label). Deepgram is the strong English default;
# Sarvam Saaras (saaras:v3 in "codemix" mode) is purpose-built for Hinglish input,
# so a caller can code-switch Hindi/English and still be transcribed correctly.
DEFAULT_STT_MODEL = "deepgram"


def _build_deepgram_stt():
    """Deepgram (default). Strong English ASR; the general-purpose choice."""
    return DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))


def _build_sarvam_stt():
    """Sarvam Saaras (best for Hinglish input). codemix mode keeps the code-switch."""
    api_key = os.getenv("SARVAM_API_KEY")
    if not api_key:
        raise ValueError(
            "STT model 'sarvam' needs SARVAM_API_KEY in your .env "
            "(free credits at dashboard.sarvam.ai — no card)."
        )
    return SarvamSTTService(
        api_key=api_key,
        settings=SarvamSTTService.Settings(model=os.getenv("SARVAM_STT_MODEL", "saaras:v3")),
        mode="codemix",
    )


STT_REGISTRY = {
    "deepgram": (_build_deepgram_stt, "DEEPGRAM_API_KEY", "Deepgram Nova (EN)"),
    "sarvam": (_build_sarvam_stt, "SARVAM_API_KEY", "Sarvam Saaras (Hinglish)"),
}


def create_stt(choice: str | None = None):
    """Build an STT service. See ``create_llm`` for the choice/fallback contract."""
    choice = (choice or os.getenv("STT_MODEL", DEFAULT_STT_MODEL)).strip()
    if choice not in STT_REGISTRY:
        raise ValueError(
            f"Unknown STT model {choice!r}. Choose one of: {', '.join(STT_REGISTRY)}"
        )
    logger.info(f"STT: {choice}")
    return STT_REGISTRY[choice][0]()


# TTS switcher — same idea. Each key maps to (factory, API-key env var, UI label).
# Providers differ a lot in their constructors (voice ids vs. speaker+model+language),
# so a factory per provider is cleaner than one shared row. The active profile's
# tts_language flows into language-aware engines (Sarvam) so Hinglish is spoken right.
DEFAULT_TTS_MODEL = "cartesia"


def _build_cartesia_tts():
    """Cartesia (default). Single English-leaning voice; ignores tts_language."""
    return CartesiaTTSService(
        api_key=os.getenv("CARTESIA_API_KEY"),
        settings=CartesiaTTSService.Settings(
            voice=os.getenv("CARTESIA_VOICE_ID", "71a7ad14-091c-4e8e-a314-022ece01c121"),
        ),
    )


def _build_sarvam_tts():
    """Sarvam (best for Hinglish). Streaming; uses the profile's tts_language."""
    api_key = os.getenv("SARVAM_API_KEY")
    if not api_key:
        raise ValueError(
            "TTS model 'sarvam' needs SARVAM_API_KEY in your .env "
            "(free credits at dashboard.sarvam.ai — no card)."
        )
    return SarvamTTSService(
        api_key=api_key,
        settings=SarvamTTSService.Settings(
            # bulbul:v2 was retired by Sarvam in Aug 2026 (the API 400s on it) and
            # v3 has a different voice roster — `anushka` no longer exists; the v3
            # picks A/B'd via scripts/generate_tts_preview.py were priya/shreya/neha.
            model=os.getenv("SARVAM_TTS_MODEL", "bulbul:v3"),
            voice=os.getenv("SARVAM_VOICE", "priya"),
            language=PROFILE.tts_language,
        ),
    )


TTS_REGISTRY = {
    "cartesia": (_build_cartesia_tts, "CARTESIA_API_KEY", "Cartesia (EN)"),
    "sarvam": (_build_sarvam_tts, "SARVAM_API_KEY", "Sarvam Bulbul (Hinglish)"),
}


def create_tts(choice: str | None = None):
    """Build a TTS service. See ``create_llm`` for the choice/fallback contract."""
    choice = (choice or os.getenv("TTS_MODEL", DEFAULT_TTS_MODEL)).strip()
    if choice not in TTS_REGISTRY:
        raise ValueError(
            f"Unknown TTS model {choice!r}. Choose one of: {', '.join(TTS_REGISTRY)}"
        )
    logger.info(f"TTS: {choice}")
    return TTS_REGISTRY[choice][0]()


# ---- Model discovery for the client dropdowns -------------------------------
# The client shows only models whose API key is actually configured, so a user
# can't pick something that will fail at connect. This endpoint is what it reads.


def available_models() -> dict:
    """List the models the client may offer, filtered to those with a key present.

    Returns a per-layer list of ``{"id", "label"}`` plus the current ``defaults``
    (from .env) so the UI can pre-select them.
    """
    llm = [
        {"id": key, "label": meta[3]}
        for key, meta in LLM_REGISTRY.items()
        if os.getenv(meta[2])
    ]
    stt = [
        {"id": key, "label": meta[2]}
        for key, meta in STT_REGISTRY.items()
        if os.getenv(meta[1])
    ]
    tts = [
        {"id": key, "label": meta[2]}
        for key, meta in TTS_REGISTRY.items()
        if os.getenv(meta[1])
    ]
    return {
        "llm": llm,
        "stt": stt,
        "tts": tts,
        "defaults": {
            "llm": os.getenv("LLM_MODEL", DEFAULT_LLM_MODEL).strip(),
            "stt": os.getenv("STT_MODEL", DEFAULT_STT_MODEL).strip(),
            "tts": os.getenv("TTS_MODEL", DEFAULT_TTS_MODEL).strip(),
        },
    }


@app.get("/models")
async def list_models() -> dict:
    """Configured models per layer, for the client's selection dropdowns.

    Registered on the runner's FastAPI app at import time (bot.py runs as
    ``__main__`` before ``main()`` starts the server), so it's live before connect.
    """
    return available_models()


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    # Per-session model selection sent by the client in the connect body (see the
    # client's config.ts). Missing keys fall back to the .env defaults, so a plain
    # `uv run bot.py` (or an eval, which has no body) still works unchanged.
    selection = runner_args.body if isinstance(runner_args.body, dict) else {}

    logger.info(
        f"Starting bot | business={PROFILE.key} ({PROFILE.display_name}) | "
        f"tools={[t.__name__ for t in TOOLS]} | "
        f"selection={{'stt': {selection.get('stt')!r}, 'llm': {selection.get('llm')!r}, "
        f"'tts': {selection.get('tts')!r}}}"
    )

    # Each service is chosen by the client (or .env default). Built here, per
    # session, so two callers can run different stacks against the same server.
    stt = create_stt(selection.get("stt"))
    tts = create_tts(selection.get("tts"))
    llm = create_llm(selection.get("llm"))

    # Listing the tools on the context registers them with the LLM (direct
    # functions carry their own schema + handler — see tools.py). Empty for a
    # profile with no tools, which the context treats as "no tools".
    context = LLMContext(tools=TOOLS)
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=SileroVADAnalyzer()),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    # Surfaces the per-stage TTFB metrics as a readable per-turn ladder (and
    # writes JSONL for the scorecard). See latency.py.
    #
    # The mode is derived from the transport rather than an env var or a flag, so
    # it can't be forgotten: `-t eval` is the only way `create_transport` returns
    # an EvalTransport (runner.utils builds it from EvalRunnerArguments), and
    # every other transport — smallwebrtc for a browser call, Daily, telephony —
    # is a real session. An eval turn's timings are inflated by the harness's own
    # STT/TTS/judge sharing the machine, so the scorecard keeps them apart.
    mode = "eval" if isinstance(transport, EvalTransport) else "live"
    latency_observer = create_latency_observer(jsonl_path=LATENCY_JSONL_PATH, mode=mode)
    # Interruption handling is already wired (Silero VAD + InterruptionFrame);
    # this measures it — one row per time the caller talks over the bot. Same
    # `mode` provenance, for the same reason. See bargein.py.
    bargein_observer = create_bargein_observer(jsonl_path=BARGEIN_JSONL_PATH, mode=mode)

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[latency_observer, bargein_observer],
        # Shared, by reference, into every tool handler as params.app_resources.
        app_resources=DATA,
    )

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation with a business-appropriate greeting.
        context.add_message({"role": "developer", "content": PROFILE.greeting})
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # Behavioral evals: run with `-t eval` to drive this bot via `pipecat eval`.
        "eval": lambda: EvalTransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
